# Deploy the documentation to GH pages automatically.
# ref: https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - name: Setup Pages
        uses: actions/configure-pages@v2
      
      # Install dependencies and build site
      - run: pip install -r requirements.txt

      - name: Create auth.json
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "{\"github_personal_token\": \"$GITHUB_ACCESS_TOKEN\"}" > docs/scripts/auth.json

      - name: Download latest GitHub data
        run: |
          cd docs/scripts
          python fetch-data.py

      - run: sphinx-build docs docs/_build/html
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # Upload to GH Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'docs/_build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Upload Logs and Build
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-logs
          path: docs/_build
